### ISSUE TITLE
Ending URL slash throws error 404

### ISSUE THREAD

**Issue by natuk** [Semantic-Data-for-Humanities/OntoME#6]
This works:
`https://ontome.net/class/756`

This does not work (note the slash in the end):
`https://ontome.net/class/756/`

which might be confusing for people.

**Comment by valamercery** [comment]
A new URL indicating the namespace has been set up to resolve this problem:

`https://ontome.net/class/756/namespace/3`

URIs have also been set up, and I suggest that you use them rather than the URLs:

Official URI (human readable one): `https://ontome.net/ns/sdhss/C4`
OntoME URI (technical one): `https://ontome.net/ontology/c756`

**Comment by natuk** [comment]
Hi @valamercery , I think that maybe the problem I reported persists, although maybe it is not a problem strictly speaking, i.e.:

this `https://ontome.net/ontology/c756` works, but
this `https://ontome.net/ontology/c756/` throws an error.

I appreciate that URIs should be used with precision, so it is not really an error in the technical sense, but I was just thinking whether adding a redirection would be easy - not a problem if not.

**Comment by valamercery** [comment]
Hi @natuk sorry for the delay in replying. I've created a new [discussion](https://github.com/orgs/geovistory/discussions/18) on this topic in the Geovistory space, which brings together all feedback on the Geovistory ecosystem, including OntoME.
